### ISSUE TITLE
V1.0.23.ipv6 doesn't work

### ISSUE THREAD

**Issue by 676407926** [Tiarait/HTTP-FS-file-server#3]
In versions 1.0.22 and 1.0.23, ipv6 can't work normally. The garbled code problem of 1.0.22webdav function when accessed through a web browser will also appear in 1.0.23. (The video feedback is only 1.0.21 and 1.0.23.)

https://github.com/Tiarait/HTTP-FS-file-server/assets/100478073/0c0b658c-096b-4e92-ba7a-bbdabfc7a3e7

**Comment by Tiarait** [comment]
Oh, I think I understand. The fact is that `/files/` is a web interface with styles and scripts, and `/webdav/` is a purely [XML scheme (API)](http://www.webdav.org/specs/rfc4918.xml#rfc.section.4.3.1) for webdav clients and I duplicate it using the HTTP/S protocol as well.

[How connect webdav on macOS](https://support.apple.com/guide/mac-help/mchlp1546/mac)
[How connect webdav on windows](https://help.dreamhost.com/hc/en-us/articles/216473357-Accessing-WebDAV-with-Windows)
[Webdav client Chrome extension](https://chromewebstore.google.com/detail/file-management-webdav/famepaffkmmhdefbapbadnniioekdppm)

In the next update I will try to write a simple interface for `/webdav/` for `http/s` protocol without using styles and scripts so that there is no confusion. Like this
<img width="340" alt="image" src="https://github.com/Tiarait/HTTP-FS-file-server/assets/25516389/a28f8953-14e2-4e00-92f2-d737a8959ef2">

**Comment by Tiarait** [comment]
fixed in 1.0.24
