### ISSUE TITLE
IPv6 does not work

### ISSUE THREAD

**Issue by ddns6** [Tiarait/HTTP-FS-file-server#7]
I'm sorry I've given up on HTTP FS, it's not very friendly to ipv6 since v1.0.22, and v1.0.27 still doesn't support it!
![Screenshot_2024-02-06-12-49-24-964_tiar ua slf_124946](https://github.com/Tiarait/HTTP-FS-file-server/assets/100478073/34b302e6-ac71-47cd-ae5a-279603890f3a)

**Comment by Tiarait** [comment]
Thanks for showing this. Yes, the problem is inside the code, I can use ipv6, for example http://[::ffff:c0a8:1ffa]:8080/, but inside other parts use ipv6. And the client will receive an error like `Uncaught DOMException` or other

`Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://192.168.31.250:8080/files/Download/' cannot be created in a document with origin 'http://[::ffff:c0a8:1ffa]:8080' and URL 'http://[::ffff:c0a8:1ffa]:8080/files/'`

I will fix this in the next version and add a switch for the desired format between ipv4 ipv6 and localhost (for QR and internal functions)
